/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DuoCalendar: typeof import('./components/svg/cyber-duotone/DuoCalendar.vue')['default']
    DuoJobMagnifier: typeof import('./components/svg/cyber-duotone/DuoJobMagnifier.vue')['default']
    DuoPen: typeof import('./components/svg/cyber-duotone/DuoPen.vue')['default']
    GAppBar: typeof import('./components/app-bar/GAppBar.vue')['default']
    GAppBarLogo: typeof import('./components/app-bar/GAppBarLogo.vue')['default']
    GAppBarMenuRight: typeof import('./components/app-bar/GAppBarMenuRight.vue')['default']
    HomeHero: typeof import('./components/pages/homepage/hero/HomeHero.vue')['default']
    HomeHeroActionButtons: typeof import('./components/pages/homepage/hero/HomeHeroActionButtons.vue')['default']
    HomeHeroChip: typeof import('./components/pages/homepage/HomeHeroChip.vue')['default']
    HomeIntroCard: typeof import('./components/pages/homepage/HomeIntroCard.vue')['default']
    HomeIntroCards: typeof import('./components/pages/homepage/HomeIntroCards.vue')['default']
    KiveLogo: typeof import('./components/svg/kive/KiveLogo.vue')['default']
    MasonryGallery: typeof import('./components/images/MasonryGallery.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsButton: typeof import('./components/buttons/SettingsButton.vue')['default']
    SquareImageCard: typeof import('./components/cards/SquareImageCard.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    'ThemeSwitch.client': typeof import('./components/ThemeSwitch.client.vue')['default']
  }
}
