/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthProvider: typeof import('./components/providers/AuthProvider.vue')['default']
    BaseDialog: typeof import('./components/dialogs/BaseDialog.vue')['default']
    ComicsActionButtons: typeof import('./components/buttons/ComicsActionButtons.vue')['default']
    Duo404: typeof import('./components/svg/Duo404.vue')['default']
    DuoImage: typeof import('./components/svg/DuoImage.vue')['default']
    DuoNoresults: typeof import('./components/svg/DuoNoresults.vue')['default']
    DuoPerson: typeof import('./components/svg/DuoPerson.vue')['default']
    GAppBar: typeof import('./components/app-bar/GAppBar.vue')['default']
    GAppBarLogo: typeof import('./components/app-bar/GAppBarLogo.vue')['default']
    GAppBarProfileMenu: typeof import('./components/app-bar/GAppBarProfileMenu.vue')['default']
    HomeHero: typeof import('./components/pages/homepage/hero/HomeHero.vue')['default']
    HomeHeroChip: typeof import('./components/pages/homepage/HomeHeroChip.vue')['default']
    KiveLogo: typeof import('./components/svg/kive/KiveLogo.vue')['default']
    LoginDialog: typeof import('./components/authentication/LoginDialog.vue')['default']
    ProfileDrawer: typeof import('./components/navigation/ProfileDrawer.vue')['default']
    RoundedSquareAvatar: typeof import('./components/avatars/RoundedSquareAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsButton: typeof import('./components/buttons/SettingsButton.vue')['default']
    SNavBar: typeof import('./components/navigation/SNavBar.vue')['default']
    SNavBarOrganization: typeof import('./components/navigation/SNavBarOrganization.vue')['default']
    SquareImageCard: typeof import('./components/cards/SquareImageCard.vue')['default']
  }
}
