/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthDialog: typeof import('./components/authentication/AuthDialog.vue')['default']
    AuthProvider: typeof import('./components/providers/AuthProvider.vue')['default']
    BaseDialog: typeof import('./components/dialogs/BaseDialog.vue')['default']
    ComicsActionButtons: typeof import('./components/buttons/ComicsActionButtons.vue')['default']
    Duo404: typeof import('./components/svg/Duo404.vue')['default']
    DuoCalendar: typeof import('./components/svg/cyber-duotone/DuoCalendar.vue')['default']
    DuoImage: typeof import('./components/svg/DuoImage.vue')['default']
    DuoJobMagnifier: typeof import('./components/svg/cyber-duotone/DuoJobMagnifier.vue')['default']
    DuoNoresults: typeof import('./components/svg/DuoNoresults.vue')['default']
    DuoPen: typeof import('./components/svg/cyber-duotone/DuoPen.vue')['default']
    DuoPerson: typeof import('./components/svg/DuoPerson.vue')['default']
    GAppBar: typeof import('./components/app-bar/GAppBar.vue')['default']
    GAppBarLogo: typeof import('./components/app-bar/GAppBarLogo.vue')['default']
    GAppBarMenuRight: typeof import('./components/app-bar/GAppBarMenuRight.vue')['default']
    GAppBarProfileMenu: typeof import('./components/app-bar/GAppBarProfileMenu.vue')['default']
    HomeHero: typeof import('./components/pages/homepage/hero/HomeHero.vue')['default']
    HomeHeroActionButtons: typeof import('./components/buttons/HomeHeroActionButtons.vue')['default']
    HomeHeroChip: typeof import('./components/pages/homepage/HomeHeroChip.vue')['default']
    HomeIntroCard: typeof import('./components/pages/homepage/HomeIntroCard.vue')['default']
    HomeIntroCards: typeof import('./components/pages/homepage/HomeIntroCards.vue')['default']
    KiveLogo: typeof import('./components/svg/kive/KiveLogo.vue')['default']
    Login: typeof import('./components/authentication/Login.vue')['default']
    LoginDialog: typeof import('./components/authentication/LoginDialog.vue')['default']
    MasonryGallery: typeof import('./components/images/MasonryGallery.vue')['default']
    RoundedSquareAvatar: typeof import('./components/avatars/RoundedSquareAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsButton: typeof import('./components/buttons/SettingsButton.vue')['default']
    SquareImageCard: typeof import('./components/cards/SquareImageCard.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    'ThemeSwitch.client': typeof import('./components/ThemeSwitch.client.vue')['default']
  }
}
